# Generated by Django 2.1.3 on 2018-11-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181111_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='image',
        ),
        migrations.AddField(
            model_name='goods',
            name='image_id',
            field=models.CharField(blank=True, max_length=500, verbose_name='产品图片'),
        ),
    ]
