# Generated by Django 2.1.2 on 2018-11-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='open_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='OpenId'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wechat',
            field=models.CharField(blank=True, max_length=100, verbose_name='微信'),
        ),
    ]
