# Generated by Django 2.1.3 on 2018-11-12 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20181112_1050'),
        ('user', '0002_auto_20181107_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
